In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [3]:
dataset = pd.read_csv("nba.csv")
dataset.shape

(458, 9)

In [4]:
dataset.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [5]:
dataset.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [6]:
dataset.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [7]:
mode = dataset['College'].mode()[0]
dataset['College'].fillna(mode,inplace=True)

In [8]:
dataset['Salary'].fillna(dataset['Salary'].mean(),inplace=True)

In [9]:
dataset.shape

(458, 9)

In [10]:
dataset.isnull().sum()

Name        1
Team        1
Number      1
Position    1
Age         1
Height      1
Weight      1
College     0
Salary      0
dtype: int64

In [11]:
dataset.dropna(inplace=True)

In [12]:
dataset.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [13]:
dataset['Height'].value_counts()

6-9     59
6-10    47
6-7     45
6-8     43
6-6     42
6-11    40
6-3     33
6-5     32
6-4     29
7-0     27
6-1     16
6-2     16
6-0     10
7-1      7
7-3      4
5-11     3
7-2      3
5-9      1
Name: Height, dtype: int64

In [15]:
heightgroups = dataset.groupby(dataset['Height'])

In [16]:
heightgroups.get_group('6-11')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
55,Nerlens Noel,Philadelphia 76ers,4.0,PF,22.0,6-11,228.0,Kentucky,3457800.0
56,Jahlil Okafor,Philadelphia 76ers,8.0,C,20.0,6-11,275.0,Duke,4582680.0
60,Christian Wood,Philadelphia 76ers,35.0,PF,20.0,6-11,220.0,UNLV,525093.0
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177.0
81,Festus Ezeli,Golden State Warriors,31.0,C,26.0,6-11,265.0,Vanderbilt,2008748.0
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,6-11,273.0,Kentucky,289755.0
91,Cole Aldrich,Los Angeles Clippers,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
113,Ryan Kelly,Los Angeles Lakers,4.0,PF,25.0,6-11,230.0,Duke,1724250.0
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
163,Bobby Portis,Chicago Bulls,5.0,PF,21.0,6-11,230.0,Arkansas,1391160.0
167,Channing Frye,Cleveland Cavaliers,9.0,PF,33.0,6-11,255.0,Arizona,8193029.0
173,Sasha Kaun,Cleveland Cavaliers,14.0,C,31.0,6-11,260.0,Kansas,1276000.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
204,Ian Mahinmi,Indiana Pacers,28.0,C,29.0,6-11,250.0,Kentucky,4000000.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
209,Shayne Whittington,Indiana Pacers,42.0,PF,25.0,6-11,250.0,Western Michigan,845059.0
211,Giannis Antetokounmpo,Milwaukee Bucks,34.0,SF,21.0,6-11,222.0,Kentucky,1953960.0
216,John Henson,Milwaukee Bucks,31.0,PF,25.0,6-11,229.0,North Carolina,2943221.0
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500.0
224,Miles Plumlee,Milwaukee Bucks,18.0,C,27.0,6-11,249.0,Duke,2109294.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,Kentucky,5200000.0
239,Dwight Powell,Dallas Mavericks,7.0,PF,24.0,6-11,240.0,Stanford,845059.0
240,Charlie Villanueva,Dallas Mavericks,3.0,PF,31.0,6-11,232.0,Connecticut,947276.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,Kentucky,22359364.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
316,Mike Muscala,Atlanta Hawks,31.0,PF,24.0,6-11,240.0,Bucknell,947276.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,Kentucky,9756250.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,Kentucky,11217391.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,Kentucky,13000000.0
391,Joffrey Lauvergne,Denver Nuggets,77.0,C,24.0,6-11,220.0,Kentucky,1709719.0
399,Gorgui Dieng,Minnesota Timberwolves,5.0,C,26.0,6-11,241.0,Louisville,1474440.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,Kentucky,8500000.0
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,Kentucky,12100000.0
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0

In [17]:
heightgroups['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
Height,,,,,,,,
5-11,3.0,5.891553e+05,7.926627e+05,55722.0,133733.0,211744.0,8.558720e+05,1500000.0
5-9,1.0,6.912869e+06,NaN,6912869.0,6912869.0,6912869.0,6.912869e+06,6912869.0
6-0,10.0,5.784075e+06,6.337144e+06,947276.0,2437500.0,3934473.5,4.846419e+06,21468695.0
6-1,16.0,5.217919e+06,4.286013e+06,700902.0,1646160.0,3402626.5,8.633373e+06,13500000.0
6-10,47.0,5.185375e+06,5.063120e+06,222888.0,1054584.5,3815000.0,7.025766e+06,19689000.0
6-11,40.0,6.544397e+06,6.906416e+06,245177.0,1362370.0,3107656.0,1.143804e+07,22359364.0
6-2,16.0,3.523777e+06,3.631376e+06,525093.0,947276.0,1553220.0,4.882013e+06,13437500.0
6-3,33.0,5.821784e+06,5.668225e+06,189455.0,1662360.0,4053446.0,8.000000e+06,20093064.0
6-4,29.0,4.646163e+06,5.275308e+06,134215.0,1015421.0,2525160.0,5.192520e+06,20000000.0
6-5,32.0,4.391786e+06,4.114296e+06,55722.0,1160040.0,3129420.0,6.015152e+06,16407500.0
6-6,42.0,3.586813e+06,4.518975e+06,167406.0,955794.0,1903380.0,4.317674e+06,25000000.0
6-7,45.0,3.504402e+06,4.337857e+06,30888.0,947276.0,1535880.0,4.000000e+06,16407500.0
6-8,43.0,5.950412e+06,6.133934e+06,83397.0,1259700.0,3425510.0,9.321234e+06,22970500.0
6-9,59.0,4.157787e+06,4.517154e+06,111444.0,1053814.0,2500000.0,5.250000e+06,20158622.0
7-0,27.0,5.287712e+06,4.675298e+06,947276.0,2003580.0,4204200.0,7.574380e+06,19689000.0
7-1,7.0,7.400988e+06,6.587462e+06,1175880.0,3441500.0,4950000.0,9.555017e+06,19688000.0
7-2,3.0,6.835639e+06,7.825718e+06,525093.0,2457350.0,4389607.0,9.990912e+06,15592217.0
7-3,4.0,2.307930e+06,1.484918e+06,1000000.0,1150000.0,2050000.0,3.207930e+06,4131720.0

In [18]:
dataset.Age.value_counts()

24.0    47
25.0    45
27.0    41
23.0    41
26.0    36
28.0    31
30.0    31
29.0    28
22.0    26
31.0    22
20.0    19
21.0    19
33.0    14
32.0    13
34.0    10
36.0    10
35.0     9
37.0     4
38.0     4
40.0     3
39.0     2
19.0     2
Name: Age, dtype: int64

In [19]:
bins= [19,25,31,36,40]
labels = ['19-24','25-30','31-35','36-40']
dataset['AgeGroup'] = pd.cut(dataset['Age'], bins=bins,labels=labels, right=False)

In [20]:
dataset['AgeGroup'].value_counts()

25-30    212
19-24    154
31-35     68
36-40     20
Name: AgeGroup, dtype: int64

In [21]:
dataset.groupby('AgeGroup')['Salary'].mean()

AgeGroup
19-24    2.761705e+06
25-30    5.870999e+06
31-35    6.635271e+06
36-40    3.897656e+06
Name: Salary, dtype: float64

In [22]:
dataset.groupby('AgeGroup')['Salary'].median()

AgeGroup
19-24    1.721380e+06
25-30    4.025000e+06
31-35    4.671342e+06
36-40    2.834470e+06
Name: Salary, dtype: float64

In [23]:
dataset.groupby('AgeGroup')['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
AgeGroup,,,,,,,,
19-24,154.0,2.761705e+06,3.164929e+06,30888.0,1000000.00,1.721380e+06,3.150510e+06,16407501.0
25-30,212.0,5.870999e+06,5.471951e+06,55722.0,1100602.00,4.025000e+06,8.991574e+06,22359364.0
31-35,68.0,6.635271e+06,6.238296e+06,200600.0,2096417.75,4.671342e+06,9.667979e+06,22970500.0
36-40,20.0,3.897656e+06,5.373672e+06,222888.0,947276.00,2.834470e+06,4.276685e+06,25000000.0

In [24]:
List_Of_Categories_In_AgeGroup=list(dataset['AgeGroup'].value_counts().index)

In [25]:
List_Of_Categories_In_AgeGroup

['25-30', '19-24', '31-35', '36-40']

In [26]:
list_of_salaries = list(dataset.groupby('AgeGroup')['Salary'])

In [27]:
list_of_salaries

[('19-24',
  3       1148640.0
  6       1170960.0
  8       1824360.0
  9       3431040.0
  10      2569260.0
            ...
  446    12000000.0
  447     1175880.0
  449     1348440.0
  452     2239800.0
  454      900000.0
  Name: Salary, Length: 154, dtype: float64),
 ('25-30',
  0      7.730337e+06
  1      6.796117e+06
  2      4.842684e+06
  4      5.000000e+06
  5      1.200000e+07
             ...
  450    2.050000e+06
  451    9.813480e+05
  453    2.433333e+06
  455    2.900000e+06
  456    9.472760e+05
  Name: Salary, Length: 212, dtype: float64),
 ('31-35',
  19      6300000.0
  31      1635476.0
  33     22875000.0
  34      7402812.0
  43       947276.0
            ...
  375    13000000.0
  394     4345000.0
  413     3750000.0
  415     3135000.0
  434     5016000.0
  Name: Salary, Length: 68, dtype: float64),
 ('36-40',
  46     4.842684e+06
  72     2.900000e+06
  93     5.675000e+06
  101    3.376000e+06
  102    9.477260e+05
  109    2.500000e+07
  119    9.472760e+05
  139    1.449187e+06
  183    2.170465e+06
  236    8.333334e+06
  256    9.472760e+05
  259    5.000000e+06
  260    3.542500e+06
  261    4.088019e+06
  296    9.472760e+05
  299    2.814000e+06
  343    2.854940e+06
  392    9.472760e+05
  406    9.472760e+05
  420    2.228880e+05
  Name: Salary, dtype: float64)]

Assignment 3 Part 2

In [29]:
import seaborn as sns

iris_dataset = sns.load_dataset("iris")

In [30]:
iris_dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
iris_dataset.species.value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [33]:
iris_dataset.shape

(150, 5)

In [34]:
iris_dataset.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [35]:
iris_dataset.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [39]:
def basic_statistics(df):
    print("\nIris-setosa")
    print(df[df.species=='setosa'].describe().transpose())
    print("\nIris-versicolor")
    print(df[df.species=='versicolor'].describe().transpose())
    print("\nIris-virginica")
    print(df[df.species=='virginica'].describe().transpose())
basic_statistics(iris_dataset)

Iris-setosa
              count   mean       std  min  25%  50%    75%  max
sepal_length   50.0  5.006  0.352490  4.3  4.8  5.0  5.200  5.8
sepal_width    50.0  3.428  0.379064  2.3  3.2  3.4  3.675  4.4
petal_length   50.0  1.462  0.173664  1.0  1.4  1.5  1.575  1.9
petal_width    50.0  0.246  0.105386  0.1  0.2  0.2  0.300  0.6

Iris-versicolor
              count   mean       std  min    25%   50%  75%  max
sepal_length   50.0  5.936  0.516171  4.9  5.600  5.90  6.3  7.0
sepal_width    50.0  2.770  0.313798  2.0  2.525  2.80  3.0  3.4
petal_length   50.0  4.260  0.469911  3.0  4.000  4.35  4.6  5.1
petal_width    50.0  1.326  0.197753  1.0  1.200  1.30  1.5  1.8

Iris-virginica
              count   mean       std  min    25%   50%    75%  max
sepal_length   50.0  6.588  0.635880  4.9  6.225  6.50  6.900  7.9
sepal_width    50.0  2.974  0.322497  2.2  2.800  3.00  3.175  3.8
petal_length   50.0  5.552  0.551895  4.5  5.100  5.55  5.875  6.9
petal_width    50.0  2.026  0.274650  1.4  1.800  2.00  2.300  2.5